version: '3.8'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-nextjs_website}
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - DEVELOPER_API_URL=${DEVELOPER_API_URL}
    ports:
      - "${PORT:-4000}:3000"